### ISSUE TITLE
Do not require placeholder for tooltip

### ISSUE THREAD

**Issue by domoritz** [vega/vega-tooltip#116]
https://github.com/vega/vega-tooltip/blob/master/docs/creating_your_tooltip.md#step-3-create-a-tooltip seems like a hack that we should remove before a 1.0 release.

**Comment by kanitw** [comment]
Maybe, but I would say 1.0 release can come after we do VL 2.0 release, so let's not do this yet.

**Comment by domoritz** [comment]
This is crucial for Vega-Embed.

**Comment by sirahd** [comment]
Sorry for being inactive for so long! It actually doesn't require manually adding a placeholder since it will add one if it doesn't exist  ([code](https://github.com/vega/vega-tooltip/blob/331f434e7847111fa3dfc1dbc5ab68ad4efd6e5d/src/tooltipDisplay.ts#L12)). So I'll just edit the tutorial and make a PR.
