### ISSUE TITLE
Remove deprecated keys

### ISSUE THREAD

**Issue by jheer** [vega/vega-tooltip#122]
At [parseOptions.ts#L25](https://github.com/vega/vega-tooltip/blob/master/src/parseOption.ts#L25) there is a list of keys to remove from tooltips. The list includes `_id` and `_prev`. The `_prev` property is a holdover from Vega 2 unused by Vega 3. The `_id` field is scheduled to be removed (and replaced with a custom Symbol property) beginning with  Vega v3.0.0-rc5. Also, it looks like the `layout_` keys are hold-overs from Vega 2 as well.

**Comment by domoritz** [comment]
@hydrosquall This seems a bit problematic. The change was not included in 0.27 but much much earlier.

**Comment by hydrosquall** [comment]
I think this happened because we didn’t have a tagged release of 0.26.0 on
GitHub yet.

The changelog generator uses the last tagged release on GitHub to calculate
the diff. I’ll remember to check for this the next time we update a repo -
the tsconfig schema generator didn’t have this issue because it was already
tagging all of its releases.
