### ISSUE TITLE
vega-tooltip should not have vega-lite as a dependency

### ISSUE THREAD

**Issue by ericsoco** [vega/vega-tooltip#142]
It should be possible to use `vega-tooltip` in Vega without having `vega-lite` appear in my bundle. Looks like the `vega-lite` imports are only used in the `vegaLite()` entry point, so are completely unused for the `vega()` entry point.

`vega-lite` should be in `peerDependencies` instead of `dependencies`, and should be imported through the `vega-lite()` entry point (in a module separate from the `vega()` entry point). `vega` might be able to be a peerDep too, though that matters less since it's also a dep of `vega-lite`.

**Comment by kanitw** [comment]
Hi @ericsoco, 

Thanks for filing the issue.  I definitely agree with you here.  @sirahd will help you fix this when he has time.   (Or if you're in rush, please feel free to submit a PR too.)

**Comment by domoritz** [comment]
I don't agree yet. While I get that it's not great to have to bundle Vega-Lite even if you only want tooltips for Vega, peer dependencies won't solve the problem as they are still required dependencies. I'd recommend instead that you create a bundle with a bundler that supports tree shaking so that the package doesn't become too big. 

I'm hesitant to change things here as I had many issues with Vega-Embed when I tried to make Vega-Lite or Vega peer dependencies.

**Comment by ericsoco** [comment]
Ah, that's a good point re: `peerDependencies` @domoritz. Bundling is still not an easy thing to figure out, even in 2018.

The separate entry points comment still feels useful, but perhaps you're right -- a good bundler will remove dead code paths and could prune vega-lite if `vega-lite()` is never called from the consuming application. I think.

**Comment by domoritz** [comment]
> I think.

I hope that 2018 is the year when bundlers actually do what they say ;-)

The only way to make sure is to have separate projects for Vega tooltip and Vega-Lite tooltip but that is a lot of extra effort. Thanks for your understanding @ericsoco!
