### ISSUE TITLE
Support positioning relative to marks

### ISSUE THREAD

**Issue by domoritz** [vega/vega-tooltip#200]
* Support both positionings relative to mark and to the cursor.
* Define relative offsets for both cases.
* For positioning relative to marks, let us define where the tooltip is (top, left, right, bottom). 
* For positioning relative to marks, we should have a maximum distance after which we position the tooltip relative to the cursor. 

@nyurik implemented something like this in kibana. https://github.com/elastic/kibana/pull/17632/files

**Comment by domoritz** [comment]
https://github.com/elastic/eui/blob/ff9d5aa29d7ce5cd48b8f331d7d417767c2c123e/src/services/popover/calculate_popover_position.js

**Comment by pelotom** [comment]
Does this issue cover restoring the ability to have the cursor follow the mouse as it moves? Currently it doesn't seem possible to do that with a `view.tooltip(...)` handler, because it only gets invoked once on entry and not when moving the mouse around on top of a mark element.

**Comment by nyurik** [comment]
@pelotom no, that would be a different issue with Vega itself.  This tooltip opens up only when Vega tells it to open - basically it is a simple replacement for the built-in (drawn on canvas) tooltip.

**Comment by domoritz** [comment]
@jheer mentioned that the next version of Vega will fire tooltip events as the cursor moves. With that, we will get the old behavior back (which I agree is preferred).

**Comment by pelotom** [comment]
Ah, I just filed an issue for it: https://github.com/vega/vega/issues/1263. Good to hear it's already being planned!

**Comment by ifokeev** [comment]
any updates here?

**Comment by domoritz** [comment]
I’d love to review a PR. It should be fairly straightforward to implement.

**Comment by bkfarnsworth** [comment]
It would also be great if this allowed clicking on a link inside the tooltip. Right now you can't have a link inside vega tooltips because they will immediately reposition if you try to move the mouse to click on it.

**Comment by Shians** [comment]
I'd like to pop up a tooltip locked to the mark without following the cursor. Is this possible right now?

**Comment by domoritz** [comment]
That's what this issue is about. Not, it's not implemented yet.

**Comment by marshallpete** [comment]
I have a working implementation for this. Look for a PR in the next couple of days.

**Comment by marshallpete** [comment]
Should we utilize the `offsetX` and `offsetY` options when positioning relative to the mark or should we provide a new `offset` option?

In my implementation, the tooltip can be positioned in any of the following locations:
```
type Position = 'top' | 'bottom' | 'left' | 'right' | 'top-left' | 'top-right' | 'bottom-left' | 'bottom-right';
```

Similar to the `label` transform in `vega`, the position calculation will try multiple positions till it finds one that doesn't leave the viewport.

I'm not sure what the expected behavior for `offsetY` would be when the tooltip is positioned to the `right`. Do we shift up or down?

If we used `offset` then it can be a fixed padding in the same direction as the placement. For example, placing the tooltip to the `right` with an `offset` of `10` would move the tooltip and additional 10 pixels to the right. Placing the tooltip in the `bottom-left` with a `offset` of `10` would push the tooltip to the left 7.07px and down 7.07px (making the diagonal distance 10px).

I don't love having options that are ignored in certain circumstances though... curious what others think

CC: @domoritz @nyurik
