### ISSUE TITLE
Test if this plugin works well with mark overlayed on top of line and area. 

### ISSUE THREAD

**Issue by kanitw** [vega/vega-tooltip#47]
Now we have `overlay` config for overlaying `line` and `area`. 

Test if this plugin works well with mark overlayed on top of line and area. 
https://github.com/vega/vega-lite/blob/master/examples/specs/overlay_line_short.json
https://github.com/vega/vega-lite/blob/master/examples/specs/overlay_area_short.json

**Comment by ZeningQu** [comment]
The two short overlay specs work with tooltip (see #50)

I also tested the full overlay specs:
https://github.com/vega/vega-lite/blob/master/examples/specs/overlay_line_full.json
https://github.com/vega/vega-lite/blob/master/examples/specs/overlay_area_full.json

With the full specs, I cannot customize the format of fields using tooltip `options.fields`, and the reason for that is `vl.spec.fieldDefs(vlSpec)` is returning `[]` instead of a complete list of `fieldDefs` for the full specs. (Although `vl.spec.fieldDefs` is returning the complete list of `fieldDefs` for the short specs).

I've created https://github.com/vega/vega-lite/issues/1476 for this issue
