### ISSUE TITLE
It would be nice if tooltip can show the same unit as axis

### ISSUE THREAD

**Issue by ZeningQu** [vega/vega-tooltip#67]
![tooltip unit](https://cloud.githubusercontent.com/assets/822034/18150941/b9e170f2-6f9f-11e6-9c53-eaa16f805b39.png)

**Comment by kanitw** [comment]
Basically, apply the same `format`.  (This could be `config.numberFormat` or `config.timeFormat` as well.)

**Comment by ericsoco** [comment]
Has there been any motion on this? I was about to implement a solution in my application code, but maybe the tooltip can pull from the spec / runtime.

**Comment by kanitw** [comment]
Not yet.   But if you want to submit a PR for this, that would be awesome!

**Comment by kanitw** [comment]
From quick skimming, probably need to modify [`bindData` method](https://github.com/vega/vega-tooltip/blob/master/src/tooltipDisplay.ts#L26) and [`supplementFieldOption`](https://github.com/vega/vega-tooltip/blob/master/src/supplementField.ts#L151) to read from `axis.format` / `legend.format` (and in the future,  `header.format` too).

@sirahd -- feel free to correct me as you know the codebase better.

**Comment by ericsoco** [comment]
I'm not using vega-lite, so the `supplementFieldOption` route won't do much for me.

I don't see any obvious way to access the Vega spec within vega-tooltip without digging through `view`'s internals, which doesn't sound like a good option. Since I have the spec handy in my application code that initializes the tooltip, I'll sync axis and tooltip formats in application code.

That said...in some cases it's actually useful to use different formats, since axis labels are often more succinct to provide an overview of the domain, while tooltip formatting often desires more detail / accuracy. So however this feature is implemented, it would be nice if it was easy to override.

**Comment by domoritz** [comment]
This works now.
