### ISSUE TITLE
document that `vl.tooltip` works for both types of vega flavours with `vg.embed` ?

### ISSUE THREAD

**Issue by Georgeouz** [vega/vega-tooltip#70]
The documentation does not appear to mention whether or not vl.tooltip also applies to regular vega specs when using `vg.embed`, i.e. when `mode` does not equal `vega-lite`.

**Update 1** Actually, `vl.tooltip` works just fine with `vg.embed`, whatever the vega flavour - of course, `mode` needs to be set accordingly.

**Update 2** Here's how I've tested: a) render the vega-lite spec with vega-lite, b) use the compiled vega spec to render in non-vega-lite mode. Both behave consistently.

**Update 3** Even `vg.tooltip` works within a vega-embed context and in vega-lite mode, obviously only with 2 arguments (the spec argument is not even needed). Hmm, I'll put a question mark to this issue given that I'm not sure whether all this is supposed to work as such or not.

**Comment by ZeningQu** [comment]
Hi Georgeouz, thanks for reporting this issue.

Both `vl.tooltip` and `vg.tooltip` should work in `vg.embed` context. I've added a code example in our documentation (PR #74)

> Even `vg.tooltip` works within a vega-embed context and in vega-lite mode, obviously only with 2 arguments (the spec argument is not even needed). 

Yeah, as you noticed `vg.tooltip` only require the vega view, so this will work. However, in general it is better to use `vl.tooltip` if you have a vega-lite spec because `vl.tooltip` will read the provided vega-lite spec and apply many formatting options to the tooltip. For example, `vl.tooltip` will read vega-lite [`timeUnit`](https://vega.github.io/vega-lite/docs/timeunit.html) and apply it to the tooltip. In this way, the tooltip is more consistent with the visualization, and user don't have to provide the same format twice (in the vega-lite spec and in toolitp `options`).

**Comment by Georgeouz** [comment]
Thanks for your reply. So by using result.spec, one practically looses the vega-lite goodies. That makes it clearer for me :-)
