### ISSUE TITLE
replace `vlSpec` by `result.spec` in the documentation ?

### ISSUE THREAD

**Issue by Georgeouz** [vega/vega-tooltip#71]
In the documentation for creating a tooltip, one could simply replace `vlSpec` by `result.spec`. This solution actually works, even if the spec is provided via the `url` property.

```javascript
var embedSpec = {
  mode: "vega-lite",
  spec: vlSpec
};
vg.embed("#vis-scatter", embedSpec, function(error, result) {
  // result.view is the Vega View, result.spec is the Vega Spec as compiled by vg.embed
  vl.tooltip(result.view, result.spec);
});
```

P.S.: **On second thought** it is actually weird that `result.spec` works in the above context. It shouldn't because the [original documentation](https://github.com/vega/vega-tooltip/blob/master/docs/creating_your_tooltip.md#step-3-create-a-tooltip) specifies that `vlSpec` should be a vega-lite spec and not a compiled vega spec. However, this also raises the question how to use `vl.tooltip` when the vega-lite spec is provided via `url` instead of `spec`.

On the other hand, I am grateful that `result.spec` does work with `vl.tooltip`(for now) because the documentation does not appear to mention how to use vega-tooltip with regular vega specs in a vega-embed context (`vg.tooltip` ?). Also see #70.

**Comment by ZeningQu** [comment]
Hi Georgeouz, if you provide a vega spec to `vl.tooltip`, tooltip will only partially work. For example, it will lose the consistent aggregated field titles (instead of showing `MEAN(Horsepower)`, it will just show `mean_Horsepower`). It also won't be able to apply `timeUnit`, which is provided by the vega-lite spec. And binned fields and count fields might not show up... and so on.

**Comment by Georgeouz** [comment]
> You can use d3.json to load the vega-lite spec first. Once the vlSpec is loaded, you can use 
> vg.embed and vl.tooltip as usual.

I'd agree with this solution, as a temporary workaround.

But isn't the point of vega-embed not to have to use `d3.json` ? After all, vega-embed already loads a vega-lite spec and converts it into object form. So there must be some way to retrieve the said object within vega-embed itself before compilation.

**Comment by ZeningQu** [comment]
I see your point. Right now this is what I do in [examples.js](https://github.com/vega/vega-tooltip/blob/master/examples.js):

```js
d3.json(path, function(error, vlSpec) {
  var embedSpec = {
    mode: "vega-lite",
    spec: vlSpec
  };
  vg.embed(id, embedSpec, function(error, result) {
    vl.tooltip(result.view, vlSpec, options);
  });
});
```

`d3.json` loads the vega-lite spec. `vg.embed` and `vl.tooltip` both use the loaded spec in object form.

If you want to use url, it would be nice if we could do this:

```js
var embedSpec = {
  mode: "vega-lite",
  url: vlSpecUrl
}
vg.embed(id, embedSpec, function(error, result) {
  vl.tooltip(result.view, result.vlSpec, options);
});
```

The problem is that right now we only have `result.spec` (Vega spec), not `result.vlSpec`.
